name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at (12:00 AM IST)
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:

          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: ARYPROGRAMMER/ARYPROGRAMMER # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          SHOW_LANGUAGE: true
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: Arya Singh # optional
          COMMITTER_EMAIL: arya.2023ug1104@iiitranchi.ac.in# optional
          AUTHOR_NAME: Arya Singh # optional
          AUTHOR_EMAIL: arya.2023ug1104@iiitranchi.ac.in # optional
          # you can populate email-id with secrets instead
